---
- name: Listing a Domain 
  hosts: all
  become: yes

  tasks: 

    - name: Display Status
      debug:
        msg: "Listing Full Domain"

    - name: List Apache
      slurp:
        src: /apache_status.txt
      register: apache 
      when: "'apache' in group_names"

    - name: Record Apache
      set_fact: 
        apache_status: "{{ apache[content] }}"
      when: "'apache' in group_names"

    - name: List NginX
      slurp:
        src: /nginx_status.txt
      register: nginx 
      when: "'nginx' in group_names"

    - name: Record NginX
      set_fact: 
        nginx_status: "{{ nginx[content] }}"
      when: "'nginx' in group_names"

    - name: List EAP
      slurp:
        src: /eap_status.txt
      register: eap 
      when: "'jboss_eap' in group_names"

    - name: Record EAP
      set_fact: 
        eap_status: "{{ eap[content] }}"
      when: "'eap' in group_names"

    - name: List Redis
      slurp:
        src: /redis_status.txt
      register: redis 
      when: "'redis' in group_names"

    - name: Record Redis
      set_fact: 
        redis_status: "{{ redis[content] }}"
      when: "'redis' in group_names"

    - name: Display Report
      debug:
        var: hostvar["apache"]