---
- name: Listing a Domain 
  hosts: all
  become: yes

  tasks: 

    - name: Display Status
      debug:
        msg: "Listing Full Domain"

    - name: List Apache
      set_fact: 
        apache: "{{ lookup('file', '/apache_status.txt') }}"
      when: "'apache' in group_names"

    - name: List NginX
      set_fact: 
        nginx: "{{ lookup('file', '/nginx_status.txt') }}"
      when: "'nginx' in group_names"

    - name: List EAP
      set_fact: 
        eap: "{{ lookup('file', '/eap_status.txt') }}"
      when: "'eap' in group_names"

    - name: List Redis
      set_fact: 
        redis: "{{ lookup('file', '/redis_status.txt') }}"
      when: "'redis' in group_names"

    - name: Display Report
      debug:
        var: hostvar["apache"]