---
- name: Start a full domain
  hosts: all
  become: yes

  tasks: 

    - name: Display Status
      debug:
        msg: "Starting Full Domain"

    - name: Start each component
      import_tasks: start_components.yml

    - name: Start each service
      import_tasks: start_services.yml

    - name: Start Domain
      copy: 
        content: "The Domain is Started\n"
        dest: /{{ item }}_status.txt
      loop: "{{ group_names | select('match','domain_*') | list }}"


