---
- name: Start a full domain
  hosts: all
  become: yes

  tasks: 

    - name: Display Status
      debug:
        msg: "Starting Full Domain"

    - name: Start each component
      import_tasks: start_components.yml

    # - name: Start each service
    #   import_tasks: start_service.yml

    # - name: Start Domain
    #   copy: 
    #     content: "The Domain is Started"
    #     dest: /domain_status.txt

