---
- name: Stop a full domain
  hosts: all
  become: yes

  tasks: 

    - name: Display Status
      debug:
        msg: "Stopping Full Domain"

    - name: Stop each component
      import_tasks: stop_components.yml

    - name: Stop each service
      import_tasks: stop_services.yml

    - name: Stop Domain
      copy: 
        content: "The Domain is STOPPED\n"
        dest: /{{ item }}_status.txt
      loop: "{{ group_names | select('match','domain_*') | list }}"