---
- name: Remove Services Configuration
  hosts: all
  become: yes

  tasks: 

    - name: Unconfigure Services
      debug:
        msg: "Removing Service Config"

    - name: Remove Service Configuration 
      file: 
        state: absent
        path: "/{{ item }}_config.txt"
      loop: "{{ group_names | select('match','service-*') | list }}"